site_name: JR Drew Content Brainstorm
site_description: "JRPM platform technical & product documentation"
repo_url: https://github.com/Diatonic-AI/jr-drew-content-brainstorm
edit_uri: edit/feat/forms-rhf-shadcn-firebase/docs/

docs_dir: docs
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - roamlinks
  - awesome-pages
  - mermaid2

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Diatonic-AI

nav:
  - Home: index.md
  - Guides:
      - Overview: guide/index.md
  - Reference:
      - API: reference/index.md
  - Architecture:
      - Platform: 02-Architecture/architecture/index.md
      - Decisions: 05-Decisions-ADRs/index.md
  - Runbooks:
      - Operations: 04-Runbooks/index.md

dev_addr: 0.0.0.0:8000
