name: Docs Deploy

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-deploy.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install MkDocs toolchain
        run: |
          pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-mermaid2
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force